// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
