// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckURL() {
  return window['go']['main']['App']['CheckURL']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetAddress(arg1) {
  return window['go']['main']['App']['SetAddress'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}
