// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function HideWindow():Promise<void>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function Quit():Promise<void>;

export function ShowWindow():Promise<void>;
