// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function CheckURL():Promise<boolean>;

export function GetConfig():Promise<config.Config>;

export function GetLoginStatus():Promise<boolean>;

export function GetStatus():Promise<number>;

export function HideWindow():Promise<void>;

export function Quit():Promise<void>;

export function SetAddress(arg1:string):Promise<boolean>;

export function ShowWindow():Promise<void>;

export function StartProxy():Promise<boolean>;

export function StopProxy():Promise<boolean>;
