name: Wails build

on:
  push:
    tags:
      # Match any new tag
      - "*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: "v2hnch-linux-amd64"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "v2hnch-linux-arm64"
            platform: "linux/arm64"
            os: "ubuntu-24.04-arm"
          # - name: "App"
          #   platform: "windows/amd64"
          #   os: "windows-latest"
          # - name: "App"
          #   platform: "darwin/universal"
          #   os: "macos-latest"
          #   nsis: false
    
    permissions:
      packages: write

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@main
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: "1.24"
